---
language: ruby
script:
  - bundle exec rake spec validate lint
rvm:
  - 2.3.1  
env:
  - PUPPET_GEM_VERSION="∼> 2.7.0"
  - PUPPET_GEM_VERSION="∼> 3.0.0"
  - PUPPET_GEM_VERSION="∼> 3.1.0"
  - PUPPET_GEM_VERSION="∼> 3.2.0"
notifications:
  email: false
