language: ruby
script:
  - bundle exec rake spec validate lint
rvm:
  - 2.3.1
env:
  matrix:
    - 'PUPPET_GEM_VERSION="∼> 2.7.0"'
    - 'PUPPET_GEM_VERSION="∼> 3.0.0"'
    - 'PUPPET_GEM_VERSION="∼> 3.1.0"'
    - 'PUPPET_GEM_VERSION="∼> 3.2.0"'
deploy:
  provider: puppetforge
  user: mauriciosousa
  password:
    secure: "mi6hyrr7p+yyQD275nlgu+EzCGtjKLMyR0vgr25PPXbRuP/LCUoyZZY77lNCWbjXjRvX/6p/O+Tf1oStCiD5SAMlIU5ho3gRSeD24RBx7lPpTmTABu/TgE1MksSZUHlayL+QUZ7oORDHHnQeXXeIjtsdsCVo7S3xdD+G+hVHawOQLJaTXZi3pjQXUo3l1ToCyrOWvSPaUF0EbDk3jzt0vA3492GF+ZXLQ9lPiHZM0f6AYUbFTled/4realUikfKKf3FwlTA1crEm0wWg6Du3O4RHzYS+aLs6QYumYcWIJWGo53GPb1fC20PPGDWImIuInfJkK8rFBl2U6Kl8bXI9Rx6G2BgKngw5JlvB5FEO37/SgFqv+lne5uxwdnZqkLOUS4J8MJheG/ipqWWkxmvy7ryeBPpgTBnQkcA3pdtc+fQ/q51QQqu6SI8o3Op0b1grWINQow/4t8GFD7FMn/Dlb4uQ13JhtfnFyn7LTKzPUkK4vhwUJ1CEnsQJCzdKk9QibqJNvwXEvY6Bd8jjuklpCzC1K9arhTIM6sqI6d16McUieELzmpD0Z39TJCghMlQltQXl/c2PuNAPo26K+2zy/ms0erTF6/CzehMcmg8J17yPQZ1JFoo5ItrmI3JcJkuYiuAFLDbntGrZzcq9yuAlGB0P1MV9mM+MSBqOX21xC+0="
  on:
    tags: true
    all_branches: true
notifications:
  email: false