language: ruby
script:
  - bundle exec rake spec validate lint
rvm:
  - 2.3.1
env:
  matrix:
    - 'PUPPET_GEM_VERSION="∼> 2.7.0"'
    - 'PUPPET_GEM_VERSION="∼> 3.0.0"'
    - 'PUPPET_GEM_VERSION="∼> 3.1.0"'
    - 'PUPPET_GEM_VERSION="∼> 3.2.0"'
deploy:
  provider: puppetforge
  user: mauriciosousa
  password:
    secure: "3vPOTFYBK4fv0fWirZD2DnpvMEi5SM88DnR7jCVyyTPwndJEecIo3NexjHZx0L146MNYP7AJrhbaC6r2Fcenbc1pFWiPD6j0K8qwLpN5WcLjBGyKmJ+IGv1fCSFSUKWV5I5ehAtDQAcuIMMK9XDEe+OuonohGn4eFmCEGhcD0yg1jy8RAAmOfy1wafhqbfL1uDp3XI85H7eFx+zuU95x+I4ZRLsXyT9KAskV5Y1t8cXfp8Ezaa2YfxvdPYa52o9Rk4yAszji8rlkNxayESwvPQkYf7qNvp3aajBbHB9BJUBDNeEGghfFA0qikdzKx/k78fgW+PEo+guME/1eDC5IHz3jHxMRnpW15Kcl8T/hhNhiYKLN6LezEC200m11THROeQ7ZeaXrPGwV/y4mf+3FvtFezT+zzR+B9eD/bNdpMUqm2aQn/MUBkT5+erRMUvDgJokugRPWMBqD+PtuYiFbcu77hBJEg/yzR4Fb+gP3DC3BpVdtDc7YHlw4693rEpbJ4YVwKMV+9lwoNqk1PtK54b769MB/CuOZ60xesdkiWfgODN0wiVLVGCfon7I+goakYvvZCcYbbo6hX8dGH3qd+aHNLAMe8XMQs7IgYZOh7MYhyce5TLbccb9q+FHpW83xD/Y5Wqb6iAJJ/7dgRfERvIrXxG7F41A9v2TbojFRUdk="  on:
    tags: true
    all_branches: true
notifications:
  email: false
