language: ruby

script:
  - 'rake spec validate lint'
matrix:
  include:
  - rvm: 1.9.3
    env: PUPPET_VERSION="2.7"
  - rvm: 2.1.5
    env: PUPPET_VERSION="3.0"
  - rvm: 2.3.6
    env: PUPPET_VERSION="4.0"
  - rvm: 2.4.0
    env: PUPPET_VERSION="5.0" DEPLOY_TO_FORGE=yes
deploy:
  provider: puppetforge
  user: mauriciosousa
  password:
    secure: "1CxkcO189QhIT1PgEu9Hgb/w2yJMDtm2isUABW29cUwOz7t+BlWS0OxdGeRvbOLblE4b9q3KksonD+LlcQFgNlNPQARWj8I8ZKNApsT+v5wG9ZFq9ZwH74J+Nu11L/4NovtGyRgCgMglssdxcZTHOggmujl9ri6gSreysvk5qLHyXDPtlc9jPd+waNwfOdUSr8Ib06v4E9h5Bk/1iQRaS/loQmdrMMtu8H7SLtuJpEKTcjUqo7zD9gGEowBjFGE1IwtOw/Lz3NWKnWbvoXj+uDMh2XUB3sxy3fGGdLeoVO1MeRWiXP4EgI+17Qrrs2+eIco4VqBzG+JCWt3VinnJ6KH3oEH7Nx4N0KN1nO5omN2qWI1D2lkmZRzATrqsIl8tDAsZ6ujcgwKFFm2lu3bx8gZEi62dphY0LRSXZzFuew/tkXyPt2aj9yWt/WShYZt84Bf/xmLACbfiVMxuW+SnHo+s+v/GIhAOgzioPeci2jGeQgeS06BPJl6jvmGNZ76ICuX8aGV5udkHjZqYMHovO3xH+6BlkKYlwNmySZwdygveAl39BtPbuinz55PE4unwlobWP+y6BVv7xro/Ls37/v3QQY9x9MJoxs3kPKXmqjXYA2W3gGYn8y7sJe7/+N6cDWnJw91qcpq3cSPECIc/fdVnQYbUiX+6gcw8ZxjBZi8="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
notifications:
  email: false
